### ISSUE TITLE
Interesting project, how to run it ?

### ISSUE THREAD

**Issue by jinyeng** [phaetto/selenium-reinforcement-learning#16]
This is a very interesting project. Wanted to try it out, but clueless on how to run it ? 

I see there is Index_EndToEndOrder.cs with 3 methods and need to run in the same order but how to launch the test ? I dont see anything in Visual Studio test explorer. Need to start test from command line ? Should it launch a chrome browser ? 

Would appreciate input.

**Comment by phaetto** [comment]
Hey @jinyeng, thanks for reaching out.

After building the project successfully, you should be able to see the tests in Visual Studio, there is no extra setup needed. Try to clean up and install nuget packages again.

Check if you have any build errors or missing .NET SDKs.

**Comment by phaetto** [comment]
Feel free to reopen another issue if you need any help, I will be closing this one.

**Comment by madhurikumar2022** [comment]
Hi, i was able to run the first test but the second and third is failing. Is that expected? Can you please help what should be the expected run status for the second and third tests.
