### ISSUE TITLE
first test runs fine but the second and third is failing. Is that expected? 

### ISSUE THREAD

**Issue by madhurikumar2022** [phaetto/selenium-reinforcement-learning#18]
Hi, i was able to run the first test but the second and third is failing. Is that expected? Can you please help what should be the expected run status for the second and third tests.

**Comment by phaetto** [comment]
Hey @madhurikumar2022, I made an update and it should fix the reported problems. Cheers

**Comment by madhurikumar2022** [comment]
@phaetto thanks a tonn. That surely helped me understand the flow. Excellent work!!!
